#!/bin/sh
#
# WildFly control script
#
# chkconfig: - 80 20

start() {
        cd /opt/appserver/jvmstats/
        pwd
        nohup ./jvmstats.sh &
	echo
	return 0
}

stop() {
	success
	echo
}

status() {
	return 3
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		status
		;;
	*)
		## If no parameters are given, print which are avaiable.
		echo "Usage: $0 {start|stop|status|restart|reload}"
		exit 1
		;;
esac
